
x-db-url: &db-url
  DATABASE_URL: postgresql://air-bnb:airbnb1122@postgis:5432/air-bnb

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: airbnb_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./airbnbPgdata:/var/lib/postgresql/data
    networks:
      - airbnb-network

  app:
    image: ${ECR_REGISTRY}/airbnb-app:latest
    container_name: airbnb_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis:5432/${POSTGRES_DB}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge

volumes:
  airbnb_pgdata: